# Generated by Django 2.2.16 on 2020-09-28 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_ghhh"),
    ]

    operations = [
        migrations.CreateModel(
            name="VBG1",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("r1", models.BigIntegerField()),
            ],
        ),
    ]
