# Generated by Django 2.2.16 on 2020-09-28 20:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0006_auto_20200928_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='customtext',
            name='r2',
            field=models.ForeignKey(blank=True, default='GGGG', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='customtext_r2', to=settings.AUTH_USER_MODEL),
        ),
    ]
